name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm check

      - run: pnpm lint --max-warnings 0

      - run: pnpm exec playwright install chromium

      - run: pnpm test

  platform-test:
    name: Platform tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm exec playwright install

      - name: Browser test - Chrome
        run: pnpm test

      - name: Browser test - Firefox
        run: BROWSER=firefox pnpm test

      - name: Browser test - Safari
        run: BROWSER=webkit pnpm test

      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: "Node.js platform tests"
        run: |
          pnpm test run test/platform-test/node.test.ts --no-browser

      - name: "Deno platform tests"
        run: |
          deno run -A npm:vitest run test/platform-test/deno.test.ts --no-browser

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm format:check
